service: serverless-udagram-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  # TODO: Add a function definition
  GetGroups:
    handler: src/lambda/http/getGroups.handler
    events: 
      - http:
          method: get
          path: groups